// nextjs-rebuild/pages/about.tsx
import { Box, Text } from "@chakra-ui/react";

export default function About() {
  return (
    <Box w={['90%', '90%', '70%']} mx='auto' fontSize={'xl'}>
      <Text my='1em' textAlign={'center'} color={"primary.500"} fontSize={'3xl'} fontWeight={'semibold'}>ANDREA MOORE</Text>
      <Text>
        I have worked as a defense attorney representing families throughout
        West Kentucky for well over a decade. I also clerked for retired Supreme
        Court Justice Bill Cunningham when he was Circuit Judge and learned
        first hand the type of judge I would like to be. I became concerned
        after covid hit when I saw many workers in the justice system leaving
        their positions to seek new opportunities. If we lose the dedicated men
        and women that make up our local justice system we all lose out. I want
        to put the focus back on these employees and do any and everything I can
        to assist them in bringing forth justice to our community. I want to
        make their day to day work life better so the justice system can
        continue to function the way it should without high turnover due to
        these valuable people being overlooked and taken for granted.
      </Text>
      <Text mt={'1.5em'}>
        I grew up in Calloway County, Kentucky. My granddad owned the local
        Singer sewing shop and my mother was employed by the US postal service
        in Murray, while my father worked as an engineer on the river. I have
        two daughters, Savannah who loves gymnastics, and Saylor who is into
        karate. My husband, Lance Moore, is a pharmacist at a local hospital and
        we live in his home county of Marshall in the small town of Possum Trot.
      </Text>
    </Box>
  );
}

// src/router/pages/About.svelte
<div class="container">
  <div class="image-wrapper">
    <img
      alt="Image"
      src="https://firebasestorage.googleapis.com/v0/b/andrea-moore-d4354.appspot.com/o/BDE7C856-E5B0-4180-A55B-97F5691AAA4B.jpeg?alt=media&token=5e99feff-1b32-46fa-9fff-59d4133507c8"
    />
  </div>

  <div class="bio">
    <h1>ANDREA MOORE</h1>
    <p>
      I have worked as a defense attorney representing families throughout West
      Kentucky for well over a decade. I also clerked for retired supreme court
      justice Bill Cunningham when he was circuit judge and learned first hand
      the type of judge I would like to be. I became concerned after covid hit
      when I saw many workers in the justice system leaving their positions to
      seek new opportunities. If we lose the dedicated men and women that make
      up our local justice system we all lose out. I want to put the focus back
      on these employees and do any and everything I can to assist them in
      bringing forth justice to our community. I want to make their day to day
      work life better so the justice system can continue to function the way it
      should without high turnover due to these valuable people being overlooked
      and taken for granted.
    </p>
    <p>
      I grew up in Calloway County, Kentucky. My granddad
      owned the local singer sewing shop and my mother was employed by the US
      postal service in Murray, while my father worked as an engineer on the
      river. I have two daughters, Savannah who loves gymnastics, and Saylor who
      is into karate. My husband Lance Moore is a pharmacist at a local hospital
      and we live in his home county of Marshall in the small town of Possum Trot.
    </p>
  </div>
</div>

<style>
  .container {
    width: 95%;
    margin-inline: auto;
    padding-top: 2em;
    display: flex;
    gap: 4em;
    align-items: center;
    justify-content: center;
  }

  .image-wrapper {
    width: 35%;
    max-height: 75vh;
  }

  .bio {
    width: 65%;
    
    margin-inline: auto;
  }

  h1 {
    text-align: center;
    color: var(--primary-500);
    margin-bottom: 1em;
  }

  img {
    width: 100%;
  }

  p {
    margin-block: 1em;
    font-size: 1.125em;
    line-height: 30px;
  }

  @media only screen and (max-width: 1075px) {
    .container {
      flex-wrap: wrap;
    }

    .image-wrapper {
      width: 60%;
    }

    .container {
      width: 100%;
    }

    .bio {
      width: 90%;
    }
  }
</style>
